### ISSUE TITLE
The version of brax

### ISSUE THREAD

**Issue by vanzll** [ld-ing/qdhf#1]
Could you please provide the version of each required package in requirements.txt?

I encountered some bugs when I try to reproduce the results in maze. I guess it is due to the version of brax I installed is different from that used by the owners.

Traceback (most recent call last):
  File "/mnt/data/wanzl/qdhf/maze/main.py", line 17, in <module>
    from kheperax.task import KheperaxConfig, KheperaxTask
  File "/mnt/data/wanzl/qdhf/maze/kheperax/task.py", line 21, in <module>
    from kheperax.type_fixer_wrapper import TypeFixerWrapper
  File "/mnt/data/wanzl/qdhf/maze/kheperax/type_fixer_wrapper.py", line 3, in <module>
    from brax.envs import env as brax_env
ImportError: cannot import name 'env' from 'brax.envs' (/mnt/data/wanzl/conda/envs/QDHF/lib/python3.10/site-packages/brax/envs/__init__.py)

**Comment by ld-ing** [comment]
Thanks for your interest in this repo. I no longer have access to the previous environment when developing this project, so unfortunately I won't be able to provide all the versions. In terms of brax, I'm pretty sure it was using the v1 API so any version in v1 should work, e.g., 0.1.x. Hope that helps!

**Comment by Johnny221B** [comment]
I am currently trying to use your repository and have encountered several compatibility issues with JAX versions. Despite trying multiple versions of JAX, I continue to face errors.

Could you please specify which version of JAX and jaxlib was used to develop this project? Knowing the exact versions would be incredibly helpful for setting up the environment correctly.

Thank you for your support and the great work on this project!

**Comment by ld-ing** [comment]
Hi @Johnny221B @vanzll , thanks for your interest in this project. I finally found some time to work on it, and sorry for the delays. 

I have updated the requirements and did some minor refactors. Now it should work with python3.11 + requirements. Feel free to reopen if you are still hitting any errors—best of luck with your ongoing projects.
